name: Pre-merge Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Config is a valid QRScout config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout our config
        uses: actions/checkout@v4
        with:
          path: 'config'
      - name: Checkout QRScout
        uses: actions/checkout@v4
        with: 
          repository: 'FRC2713/QRScout'
          path: 'qrscout'
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /qrscout/config/schema.json
          INPUT_JSONS: /config/qr-scout-config.json
